connections {
    car-lim {
        version = 2

        local_addrs  = 172.24.133.80
        remote_addrs = 172.24.133.84

        local {
            auth = psk
            id = 172.24.133.80
        }
        remote {
            auth = psk
            id = 172.24.133.84
        }

        children {
            car-lim-child {
                local_ts  = 10.4.16.0/20
                remote_ts = 10.4.32.0/20

                esp_proposals = aes256-sha256-modp2048

                start_action = start
                dpd_action = restart
                life_time = 1h
                rekey_time = 51m
            }
        }

        proposals = aes256-sha256-modp2048
        rekey_time = 8h
        dpd_delay = 30s
        dpd_timeout = 120s
    }
}

secrets {
    ike-car-lim {
        id-1 = 172.24.133.80
        id-2 = 172.24.133.84
        secret = "PSK"
    }
}
