# Fuente común: el equipo de borde de la sede central (sjo)
server 172.24.133.76 iburst

driftfile /var/lib/chrony/drift
rtcsync

# Permitir que las VLANs internas de esta sede consulten esta fuente
allow 10.4.16.0/20

logdir /var/log/chrony
log measurements statistics tracking
