# Fuente externa de referencia (via ens33, ya permitido en el firewall - UDP 123 output)
pool 2.pool.ntp.org iburst
pool time.cloudflare.com iburst

# Registro de mediciones para análisis de desviación
driftfile /var/lib/chrony/drift
rtcsync

# Permitir que las VLANs internas de sjo consulten esta fuente
allow 10.4.0.0/20

# Permitir que lim y car (via su IP WAN) usen sjo como fuente común
allow 172.24.133.80
allow 172.24.133.84

# Actuar como servidor NTP aunque momentáneamente no tenga sincronía perfecta con el exterior
local stratum 10

logdir /var/log/chrony
log measurements statistics tracking
