# Fuente común: el equipo de borde de la sede central (sjo)
server 172.24.133.76 iburst

driftfile /var/lib/chrony/drift
rtcsync

allow 10.4.32.0/20

logdir /var/log/chrony
log measurements statistics tracking
